### PR TITLE
Add mapping from array with custom automapper

### PR DESCRIPTION
**Pull request by vasilake-v**
Initial implementation of array mapping into objects.
Supports `customMapper`, automatically property assignment or manually by using `FromKey`
I have written several tests and updated the Readme.md file with examples of usage

### CODE REVIEW

**Comment by mark-gerarts** [comment]
Hi @slava-v, thanks for the PR! I'm gonna review this over the weekend, but it's looking good on first sight :)

**Comment by mark-gerarts** [comment]
Alright, I've tested it a bit. Some remarks:

- Mapping from an array crashes when you define a `mapTo` operation. This because of the `isCollection`-check in `MapTo`. Our todo here is to add a failing test and fix it.
- You throw a `new \Exception`. This should be a domain-specific exception. (e.g. `InvalidMappingSourceException`)
- I'll probably refactor the readme changes, since I'd rather see the array documentation in its own subsection
- I'll change some lines to follow the same coding standards as the rest of the library (e.g. `if (...){` should be `if (...) {`. This is really minor!

That being said, I like the changes. We're finally able to map from arrays, thank you! Because of the `mapTo` bug, I'm gonna merge this PR into the development branch. I'll then take a look at the bug and the other remarks as well. 

As a side note, there are plans to use a decorated version of the symfony property-access component (as discussed in #16). We'll have to see how this works with arrays when we get there.

**Comment by vasilake-v** [comment]
@mark-gerarts , thanks for review :)

I can fix the PR in based on your comments ( along with `mapTo` bug + tests)..

If you want you can take the "Readme" changes :)

**Comment by vasilake-v** [comment]
Hi @mark-gerarts ,
I have 
- added the domain-specific exception instead of the generic `\Exception` class
- added a test case for `mapTo` operation
- reformatted a bit

I wasn't able to reproduce the failure you were referring to. Could you please exemplify? I'd like to know in what configuration it fails.

**Comment by vasilake-v** [comment]
@mark-gerarts ,

I have found the issue with `Operation::mapTo` with following:
A new model for test
```
class EmployeeAddressDto extends EmployeeDto
{
    public $address;
}
```
The new test that should fail
```
    public function testArrayMapping_WithMapToOperation_Fails()
    {
        $employee = [
            'id' => '1',
            'firstName' => 'Josh',
            'lastName' => 'Doe',
            'age' => '99',
            'notes' => 'bombibom',
            'address' => [
                'street' => 'asdf',
                'number' => '123'
            ]
        ];

        $config = new AutoMapperConfig();
        $config->registerArrayMapping(EmployeeAddressDto::class)
            ->forMember('address', Operation::mapTo(Address::class));

        $mapper = new AutoMapper($config);

        $mapper->map($employee, EmployeeAddressDto::class);

        $this->expectException(InvalidMappingSourceException::class);
    }
```
I have 2 possible solutions:

1. Add a argument in `mapTo` constructor and determine to handle the property as a collection or not: [my separate branch with changes](https://github.com/slava-v/automapper-plus/commit/a8b6adf3a8657bb629233ba949fbf9453b801d9b)
2. Extend the `MapTo` class into a `MapCollectionTo`. The `MapTo::getSourceValue` `return` part, into a protected method `internalMap`:

in `MapTo` class:
```
protected function getSourceValue($source, string $propertyName)
{
    ...
    return $this->internalMap($value);
}
...
protected function internalMap($value){
    $this->mapper->map($value, $this->destinationClass);
}
```

The new `MapCollectionTo` class:
```
class MapCollectionTo extends MapTo {

    protected function internalMap($value)
    {
        $this->mapper->mapCollection($value, $this->destinationClass);
    }
```

**Comment by mark-gerarts** [comment]
Sorry for the late answer, it has been a pretty busy period for me. I think passing a second argument to MapTo is a decent solution, not breaking backwards compatibility. So if you merge that branch into this, I'll be happy to accept this PR! I'll make some minor changes later on (such as the readme discussed earlier). Thanks for all the work :)

**Comment by spointecker** [comment]
@mark-gerarts @slava-v 
Is this going to be merged/released soon?

**Comment by mark-gerarts** [comment]
Hi @spointecker, I'll take a look at it in the following days. It needs some refactoring for newer changes, and if possible I want change the API a bit, to make it possible to register array mappings using the regular `registerMapping` method.

**Comment by mark-gerarts** [comment]
And as a side note, mapping from `\stdClass` is possible, so as a temporary solution you could cast your array to an object.

**Comment by spointecker** [comment]
Hi @mark-gerarts 
thanks for your quick response! Looking forward to using it.

**Comment by mark-gerarts** [comment]
Hi @spointecker. Mapping from arrays has been implemented and merged into master. You can use it in the same way as you would define mappings for regular classes (take a look at the [readme](https://github.com/mark-gerarts/automapper-plus#mapping-with-arrays) for an example). I'll let this rest on master for a few more days to let me test it thoroughly, and I'll tag a release after that. Feel free to try it out yourself too :)

Mapping *to* an array hasn't been implemented. While it would be relatively easy to do, it would require me to introduce a breaking change. I'll therefore delay it until I start working on a major release.

@slava-v, I have chosen not to merge your PR. This because I wanted to implement it in a slightly different way, with some future features in mind. I understand that this PR took quite some time and effort, and it can be frustrating not seeing it merged. I want to use this comment to thank you for your work! It's greatly appreciated. Your ideas and discussion helped a lot and I've therefore credited you in the readme.

**Pull request closed without merging**
